import { defineCommand } from 'citty';
import { writeFile, mkdir, access } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { logger } from '@mcpmake/core';
import { fail } from '@mcpmake/core';

const SOURCES = new Set(['openapi', 'har', 'postman']);
const TRANSPORTS = new Set(['stdio', 'http']);

export interface WorkflowOptions {
  /** Path to the spec, relative to the repo root (e.g. `api-spec.yaml`). */
  spec: string;
  /** Generated server directory (e.g. `./mcp-server`). */
  output: string;
  /** Source adapter. */
  source: 'openapi' | 'har' | 'postman';
  /** Optional server name. */
  name?: string;
  /** Transport mode for the generated server. */
  transport: 'stdio' | 'http';
  /** mcpmake version/tag to run in CI (e.g. `latest`, `0.1.0`). */
  version: string;
}

/** Shell-quote a value for safe interpolation into a `run:` step. */
function q(value: string): string {
  return `"${value.replace(/"/g, '\\"')}"`;
}

/**
 * Build the `.github/workflows/mcpmake.yaml` contents. Pure + testable.
 *
 * The workflow regenerates the MCP server from the spec on every change and
 * fails if the committed output is stale — the "keep generated code in sync
 * with the spec" guarantee (the Stainless-style auto-regenerate-on-spec-change
 * workflow). It also runs `mcpmake verify` for OpenAPI specs.
 */
export function buildWorkflowYaml(opts: WorkflowOptions): string {
  const runner = `npx --yes mcpmake@${opts.version}`;
  const genFlags = [
    `-o ${q(opts.output)}`,
    opts.name ? `-n ${q(opts.name)}` : '',
    opts.transport === 'http' ? '-t http' : '',
    '-f',
  ]
    .filter(Boolean)
    .join(' ');
  const generate = `${runner} from ${opts.source} ${q(opts.spec)} ${genFlags}`;
  const verify = `${runner} verify ${q(opts.spec)} -p ${q(opts.output)}`;

  const lines: string[] = [
    '# Generated by `mcpmake ci init`.',
    '# Regenerates the MCP server from the spec on every change and fails if the',
    '# committed output is out of date — keep your generated server in sync with',
    '# the API spec. Re-run `mcpmake from ...` locally and commit when this fails.',
    'name: mcpmake',
    '',
    'on:',
    '  push:',
    '    paths:',
    `      - ${q(opts.spec)}`,
    "      - '.github/workflows/mcpmake.yaml'",
    '  pull_request:',
    '    paths:',
    `      - ${q(opts.spec)}`,
    '  workflow_dispatch:',
    '',
    'jobs:',
    '  sync:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '      - uses: actions/setup-node@v4',
    '        with:',
    "          node-version: '20'",
    '      - name: Regenerate MCP server from spec',
    `        run: ${generate}`,
  ];

  // `mcpmake verify` currently supports OpenAPI specs only.
  if (opts.source === 'openapi') {
    lines.push('      - name: Verify generated server matches the spec', `        run: ${verify}`);
  }

  lines.push(
    '      - name: Fail if the generated server is out of date',
    '        run: |',
    `          if [ -n "$(git status --porcelain ${q(opts.output)})" ]; then`,
    `            echo "::error::The committed MCP server under ${opts.output} is out of date with ${opts.spec}. Regenerate it and commit the result."`,
    `            git --no-pager diff -- ${q(opts.output)}`,
    '            exit 1',
    '          fi',
    '',
  );

  return lines.join('\n');
}

const initCommand = defineCommand({
  meta: {
    name: 'init',
    description:
      'Generate a GitHub Actions workflow that regenerates + verifies the MCP server when the spec changes',
  },
  args: {
    spec: {
      type: 'positional',
      description: 'Path to the API spec, relative to the repo root (e.g. api-spec.yaml)',
      required: true,
    },
    output: {
      type: 'string',
      alias: 'o',
      description: 'Generated server directory',
      default: './mcp-server',
    },
    source: {
      type: 'string',
      alias: 's',
      description: 'Source adapter: openapi | har | postman',
      default: 'openapi',
    },
    name: {
      type: 'string',
      alias: 'n',
      description: 'Server name passed to generation',
    },
    transport: {
      type: 'string',
      alias: 't',
      description: 'Transport for the generated server: stdio | http',
      default: 'stdio',
    },
    'mcpmake-version': {
      type: 'string',
      description: 'mcpmake version/tag to run in CI (e.g. latest, 0.1.0)',
      default: 'latest',
    },
    force: {
      type: 'boolean',
      alias: 'f',
      description: 'Overwrite an existing workflow file',
      default: false,
    },
  },
  async run({ args }) {
    const source = String(args.source);
    const transport = String(args.transport);
    if (!SOURCES.has(source)) {
      await fail(`Invalid --source "${source}". Use one of: openapi, har, postman.`);
    }
    if (!TRANSPORTS.has(transport)) {
      await fail(`Invalid --transport "${transport}". Use one of: stdio, http.`);
    }

    const workflowPath = resolve('.github/workflows/mcpmake.yaml');
    const exists = await access(workflowPath).then(
      () => true,
      () => false,
    );
    if (exists && !args.force) {
      await fail(`${workflowPath} already exists. Re-run with --force to overwrite.`);
    }

    const yaml = buildWorkflowYaml({
      spec: args.spec,
      output: String(args.output),
      source: source as WorkflowOptions['source'],
      name: args.name ? String(args.name) : undefined,
      transport: transport as WorkflowOptions['transport'],
      version: String(args['mcpmake-version']),
    });

    await mkdir(dirname(workflowPath), { recursive: true });
    await writeFile(workflowPath, yaml, 'utf-8');

    logger.success(`Wrote ${workflowPath}`);
    logger.info('Commit it, and CI will keep the generated server in sync with the spec.');
  },
});

export default defineCommand({
  meta: {
    name: 'ci',
    description: 'CI integration helpers (GitHub Actions)',
  },
  subCommands: {
    init: initCommand,
  },
});
