/**
 * Builds multi-strategy selector sets for DOM elements.
 *
 * Generates selectors in priority order (most stable first):
 * data-testid > id > aria-label > name > role > CSS path > XPath
 */

import type { Page, ElementHandle } from 'playwright';
import type { SelectorSet, SelectorStrategy } from '../types/site.js';

interface SelectorCandidate {
  selector: string;
  strategy: SelectorStrategy;
  confidence: number;
}

/**
 * Build a SelectorSet for a given element on the page.
 * Tries multiple strategies and picks the most stable one as primary.
 */
export async function buildSelectorSet(page: Page, element: ElementHandle): Promise<SelectorSet> {
  const candidates: SelectorCandidate[] = [];

  const attrs = await element.evaluate((node) => {
    const el = node as Element;
    return {
      tagName: el.tagName.toLowerCase(),
      id: el.id || null,
      name: el.getAttribute('name'),
      type: el.getAttribute('type'),
      testId: el.getAttribute('data-testid') || el.getAttribute('data-test-id'),
      ariaLabel: el.getAttribute('aria-label'),
      role: el.getAttribute('role') || null,
      placeholder: el.getAttribute('placeholder'),
      textContent: el.textContent?.trim().slice(0, 80) || null,
      className: el.className || null,
    };
  });

  // 1. data-testid (most stable — intentionally placed for testing)
  if (attrs.testId) {
    candidates.push({
      selector: `[data-testid="${cssEscape(attrs.testId)}"]`,
      strategy: 'data-testid',
      confidence: 0.95,
    });
  }

  // 2. id (stable if present, but may be auto-generated)
  if (attrs.id && !looksAutoGenerated(attrs.id)) {
    candidates.push({
      selector: `#${cssEscape(attrs.id)}`,
      strategy: 'id',
      confidence: 0.9,
    });
  }

  // 3. aria-label (stable for accessible sites)
  if (attrs.ariaLabel) {
    candidates.push({
      selector: `${attrs.tagName}[aria-label="${cssEscape(attrs.ariaLabel)}"]`,
      strategy: 'aria-label',
      confidence: 0.85,
    });
  }

  // 4. name attribute (stable for form elements)
  if (attrs.name) {
    const typeQualifier = attrs.type ? `[type="${attrs.type}"]` : '';
    candidates.push({
      selector: `${attrs.tagName}[name="${cssEscape(attrs.name)}"]${typeQualifier}`,
      strategy: 'name',
      confidence: 0.85,
    });
  }

  // 5. role + text (for buttons/links with visible text)
  if (attrs.role && attrs.textContent) {
    const shortText = attrs.textContent.slice(0, 40);
    candidates.push({
      selector: `${attrs.tagName}[role="${attrs.role}"]:has-text("${cssEscape(shortText)}")`,
      strategy: 'role',
      confidence: 0.7,
    });
  }

  // 6. CSS path (always available but fragile)
  const cssPath = await buildCssPath(element);
  if (cssPath) {
    candidates.push({
      selector: cssPath,
      strategy: 'css-path',
      confidence: 0.4,
    });
  }

  // Sort by confidence descending
  candidates.sort((a, b) => b.confidence - a.confidence);

  if (candidates.length === 0) {
    // Absolute fallback: XPath
    const xpath = await buildXPath(element);
    return {
      primary: xpath,
      fallbacks: [],
      strategy: 'xpath',
      confidence: 0.2,
    };
  }

  const primary = candidates[0];
  const fallbacks = candidates.slice(1).map((c) => c.selector);

  return {
    primary: primary.selector,
    fallbacks,
    strategy: primary.strategy,
    confidence: primary.confidence,
  };
}

/**
 * Validate that a selector still resolves to an element on the page.
 * Tries the primary selector first, then fallbacks.
 * Returns the first working selector or null if all fail.
 */
export async function validateSelector(
  page: Page,
  selectorSet: SelectorSet,
): Promise<string | null> {
  const allSelectors = [selectorSet.primary, ...selectorSet.fallbacks];

  for (const selector of allSelectors) {
    try {
      const el = await page.$(selector);
      if (el) return selector;
    } catch {
      // Selector syntax may be invalid — skip
    }
  }

  return null;
}

// ─── Internal helpers ───────────────────────────────────────────────

/** Build a CSS path from element to a unique ancestor. */
async function buildCssPath(element: ElementHandle): Promise<string | null> {
  try {
    return await element.evaluate((node) => {
      const parts: string[] = [];
      let current = node as Element | null;
      const maxDepth = 5;
      let depth = 0;

      while (current && current !== document.body && depth < maxDepth) {
        let part = current.tagName.toLowerCase();
        if (current.id) {
          // CSS.escape keeps the selector valid (and injection-safe) for ids
          // containing quotes/brackets/etc. from untrusted crawled pages.
          part = `#${CSS.escape(current.id)}`;
          parts.unshift(part);
          break;
        }
        const parent = current.parentElement;
        if (parent) {
          const siblings = Array.from(parent.children).filter(
            (c) => c.tagName === current!.tagName,
          );
          if (siblings.length > 1) {
            const index = siblings.indexOf(current) + 1;
            part += `:nth-of-type(${index})`;
          }
        }
        parts.unshift(part);
        current = parent;
        depth++;
      }
      return parts.join(' > ');
    });
  } catch {
    return null;
  }
}

/** Build an XPath for the element (absolute fallback). */
async function buildXPath(element: ElementHandle): Promise<string> {
  try {
    return await element.evaluate((node) => {
      const parts: string[] = [];
      let current = node as Element | null;

      while (current && current.nodeType === Node.ELEMENT_NODE) {
        let index = 1;
        let sibling = current.previousElementSibling;
        while (sibling) {
          if (sibling.tagName === current.tagName) index++;
          sibling = sibling.previousElementSibling;
        }
        parts.unshift(`${current.tagName.toLowerCase()}[${index}]`);
        current = current.parentElement;
      }
      return '/' + parts.join('/');
    });
  } catch {
    return '//body';
  }
}

/** Check if an ID looks auto-generated (random hash, UUID-like, etc.) */
function looksAutoGenerated(id: string): boolean {
  // Random hex strings (8+ chars of only hex)
  if (/^[a-f0-9]{8,}$/i.test(id)) return true;
  // React-style IDs like :r0:, :r1a:
  if (/^:r[a-z0-9]+:$/.test(id)) return true;
  // Contains UUID-like segments
  if (/[a-f0-9]{8}-[a-f0-9]{4}/.test(id)) return true;
  // Very long IDs are usually auto-generated
  if (id.length > 40) return true;
  return false;
}

/** Escape a string for use in CSS selectors. */
function cssEscape(str: string): string {
  return str.replace(/["'\\[\](){}:.,!#$%^&*+=|~<>?/;@]/g, '\\$&');
}
